name: wordpress_portfolio
version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: portfoliodb
      MYSQL_USER: portfoliouser
      MYSQL_PASSWORD: portfoliopassword
    ports:
      - "3306:3306"
    volumes:
      - ./srv/database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: portfoliouser
      WORDPRESS_DB_PASSWORD: portfoliopassword
      WORDPRESS_DB_NAME: portfoliodb
    ports:
      - "8080:80"
    volumes:
      - ./srv/wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes # this is maping ot the themes directory in wordpress folder in srv
      - ./plugins:/var/www/html/wp-content/plugins
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: portfoliouser
      PMA_PASSWORD: portfoliopassword
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "8181:80"
    depends_on:
      - mysql
