name: Portfolio Starter Setup (FTP only)

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download WordPress (version controlled)
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget "$WP_LINK" -O wordpress.zip
          unzip -q wordpress.zip

      - name: Prepare wp-content
        run: |
          mkdir -p wordpress/wp-content
          cp -R themes wordpress/wp-content/themes
          cp -R plugins wordpress/wp-content/plugins
          cp -R mu-plugins wordpress/wp-content/mu-plugins

      - name: Deploy WordPress via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER_HOST  }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD  }}
          local-dir: ./wordpress/
          server-dir: /htdocs/
          dangerous-clean-slate: false
